<?php
namespace AmericasFarmers;

class ACFHeaderSettings
{
  public static function setupHeaderSettings()
  {
    self::setupHeaderOptionsFields();
  }
  private static function setupHeaderOptionsFields()
  {
    if( function_exists('acf_add_local_field_group') ):

      acf_add_local_field_group(array(
      	'key' => 'group_5b0ebf61c537e',
      	'title' => 'Header Settings',
      	'fields' => array(
      		array(
      			'key' => 'field_5b0ec0b26372b',
      			'label' => 'Logo Text First',
      			'name' => 'logo_text_first',
      			'type' => 'text',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array(
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      			'default_value' => '',
      			'placeholder' => '',
      			'prepend' => '',
      			'append' => '',
      			'maxlength' => '',
      		),
      		array(
      			'key' => 'field_5b0ec12a6372c',
      			'label' => 'Logo Text Second',
      			'name' => 'logo_text_second',
      			'type' => 'text',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array(
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      			'default_value' => '',
      			'placeholder' => '',
      			'prepend' => '',
      			'append' => '',
      			'maxlength' => '',
      		),
      		array(
      			'key' => 'field_5b0ec17059a48',
      			'label' => 'Primary Menu',
      			'name' => 'primary_menu',
      			'type' => 'repeater',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array(
      				'width' => '',
      				'class' => '',
      				'id' => '',
      			),
      			'collapsed' => '',
      			'min' => 0,
      			'max' => 0,
      			'layout' => 'block',
      			'button_label' => 'Add Menu Item',
      			'sub_fields' => array(
      				array(
      					'key' => 'field_5b0ec1c359a49',
      					'label' => 'Page Link',
      					'name' => 'page_link',
      					'type' => 'post_object',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      					'post_type' => array(
      						0 => 'page',
      					),
      					'taxonomy' => array(
      					),
      					'allow_null' => 0,
      					'multiple' => 0,
      					'return_format' => 'object',
      					'ui' => 1,
      				),
      				array(
      					'key' => 'field_5b0ec21559a4a',
      					'label' => 'Menu Title First',
      					'name' => 'menu_title_first',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '50',
      						'class' => '',
      						'id' => '',
      					),
      					'default_value' => '',
      					'placeholder' => '',
      					'prepend' => '',
      					'append' => '',
      					'maxlength' => '',
      				),
      				array(
      					'key' => 'field_5b0ec23e59a4b',
      					'label' => 'Menu Title Second',
      					'name' => 'menu_title_second',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '50',
      						'class' => '',
      						'id' => '',
      					),
      					'default_value' => '',
      					'placeholder' => '',
      					'prepend' => '',
      					'append' => '',
      					'maxlength' => '',
      				),
      				array(
      					'key' => 'field_5b0ec27659a4c',
      					'label' => 'Background Image',
      					'name' => 'background_image',
      					'type' => 'image',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '50',
      						'class' => '',
      						'id' => '',
      					),
      					'return_format' => 'array',
      					'preview_size' => 'thumbnail',
      					'library' => 'all',
      					'min_width' => '',
      					'min_height' => '',
      					'min_size' => '',
      					'max_width' => '',
      					'max_height' => '',
      					'max_size' => '0.5',
      					'mime_types' => '',
      				),
      				array(
      					'key' => 'field_5b0ec2db59a4d',
      					'label' => 'Menu Logo',
      					'name' => 'menu_logo',
      					'type' => 'image',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '50',
      						'class' => '',
      						'id' => '',
      					),
      					'return_format' => 'array',
      					'preview_size' => 'thumbnail',
      					'library' => 'all',
      					'min_width' => '',
      					'min_height' => '',
      					'min_size' => '',
      					'max_width' => '',
      					'max_height' => '',
      					'max_size' => '0.5',
      					'mime_types' => '',
      				),
      				array(
      					'key' => 'field_5b0ec3dc2c4c0',
      					'label' => 'Program',
      					'name' => 'program',
      					'type' => 'post_object',
      					'instructions' => 'Select Program that this represents.',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
                'post_type' => array(
                  0 => 'program',
                ),
                'return_format' => 'object',
      					'default_value' => '',
      					'placeholder' => '',
      					'prepend' => '',
      					'append' => '',
      					'maxlength' => '',
      				),
      				array(
      					'key' => 'field_5b0ec3ed2c4c1',
      					'label' => 'Sub Menu',
      					'name' => 'sub_menu',
      					'type' => 'repeater',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      					'collapsed' => '',
      					'min' => 0,
      					'max' => 0,
      					'layout' => 'table',
      					'button_label' => 'Add Submenu Item',
      					'sub_fields' => array(
      						array(
      							'key' => 'field_5b0ec3fe2c4c2',
      							'label' => 'Page Link',
      							'name' => 'submenu_link',
      							'type' => 'page_link',
      							'instructions' => '',
      							'required' => 0,
      							'conditional_logic' => 0,
      							'wrapper' => array(
      								'width' => '',
      								'class' => '',
      								'id' => '',
      							),
      							'post_type' => array(
      								0 => 'page',
      							),
      						),
      						array(
      							'key' => 'field_5b0ec41c2c4c3',
      							'label' => 'Page Title',
      							'name' => 'page_title',
      							'type' => 'text',
      							'instructions' => '',
      							'required' => 0,
      							'conditional_logic' => 0,
      							'wrapper' => array(
      								'width' => '',
      								'class' => '',
      								'id' => '',
      							),
      							'default_value' => '',
      							'placeholder' => '',
      							'prepend' => '',
      							'append' => '',
      							'maxlength' => '',
      						),
      					),
      				),
      			),
      		),
      		array(
      			'key' => 'field_5b0ec367337ac',
      			'label' => 'Secondary Pages',
      			'name' => 'secondary_pages',
      			'type' => 'repeater',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array(
      				'width' => '',
      				'class' => '',
      				'id' => '',
      			),
      			'collapsed' => '',
      			'min' => 0,
      			'max' => 0,
      			'layout' => 'table',
      			'button_label' => 'Add Item',
      			'sub_fields' => array(
      				array(
      					'key' => 'field_5b0ec375337ad',
      					'label' => 'Page Link',
      					'name' => 'page_link',
      					'type' => 'post_object',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '50',
      						'class' => '',
      						'id' => '',
      					),
      					'post_type' => array(
      						0 => 'page',
      					),
      					'taxonomy' => array(
      					),
      					'allow_null' => 0,
      					'multiple' => 0,
      					'return_format' => 'object',
      					'ui' => 1,
      				),
      				array(
      					'key' => 'field_5b0ec38a337ae',
      					'label' => 'Page Title',
      					'name' => 'page_title',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '50',
      						'class' => '',
      						'id' => '',
      					),
      					'default_value' => '',
      					'placeholder' => '',
      					'prepend' => '',
      					'append' => '',
      					'maxlength' => '',
      				),
      			),
      		),
          array(
            'key' => 'field_search_wizzywig',
            'label' => 'Search Modal No Results Message',
            'name' => 'search_no_results_content',
            'type' => 'wysiwyg',
            'instructions' => 'This content displays in the Search modal if no results are found.',
            'toolbar' => 'full',
            'media_upload' => 0,
          ),
      	),
      	'location' => array(
      		array(
      			array(
      				'param' => 'options_page',
      				'operator' => '==',
      				'value' => 'header_settings',
      			),
      		),
      	),
      	'menu_order' => 0,
      	'position' => 'normal',
      	'style' => 'default',
      	'label_placement' => 'top',
      	'instruction_placement' => 'label',
      	'hide_on_screen' => '',
      	'active' => 1,
      	'description' => '',
      ));

      endif;


  }
}
