<?php
namespace AmericasFarmers;

class ACFPostFields
{
  public static function setupPostFields()
  {
    self::setupPostFlexFields();
  }
  private static function setupPostFlexFields()
  {
    if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
    	'key' => 'group_5b353a295a58a',
    	'title' => 'Post Flex Content',
    	'fields' => array(
    		array(
    			'key' => 'field_5b353c65a25c4',
    			'label' => 'Post Flexible Content',
    			'name' => 'post_flexible_content',
    			'type' => 'flexible_content',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'layouts' => array(
    				'5b353c7a68df8' => array(
    					'key' => '5b353c7a68df8',
    					'name' => 'post-basic_content',
    					'label' => 'Basic Content',
    					'display' => 'block',
    					'sub_fields' => array(
                array(
                  'key' => 'field_post_content_width',
                  'label' => 'Content Layout',
                  'name' => 'post_content_layout',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'half-width' => '1/2 Width',
                    'threefourth-width' => '3/4 Width',
                  ),
                  'default_value' => array(
                    0 => 'half-width',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'ajax' => 0,
                  'return_format' => 'value',
                  'placeholder' => '',
                ),
                //end content width
    						array(
    							'key' => 'field_5b353a3633efb',
    							'label' => 'Basic Content',
    							'name' => 'post_basic_content',
    							'type' => 'wysiwyg',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array(
    								'width' => '',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => '',
    							'tabs' => 'all',
    							'toolbar' => 'full',
    							'media_upload' => 1,
    							'delay' => 0,
    						),
    					),
    					'min' => '',
    					'max' => '',
    				),
    				'5b353cafa25c5' => array(
    					'key' => '5b353cafa25c5',
    					'name' => 'post-full_width_color_content',
    					'label' => 'Full Width Color Content',
    					'display' => 'block',
    					'sub_fields' => array(
                array(
            			'key' => 'field_5be21eec19e1b',
            			'label' => 'Program Logo',
            			'name' => 'program_logo',
            			'type' => 'image',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array(
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'return_format' => 'id',
            			'preview_size' => 'thumbnail',
            			'library' => 'all',
            			'min_width' => '',
            			'min_height' => '',
            			'min_size' => '',
            			'max_width' => '',
            			'max_height' => '',
            			'max_size' => '',
            			'mime_types' => '',
            		),
            		array(
            			'key' => 'field_5be21eff19e1c',
            			'label' => 'Program Link',
            			'name' => 'program_link',
            			'type' => 'page_link',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array(
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'post_type' => array(
                    0 => 'program',
            			),
            			'taxonomy' => array(
            			),
            			'allow_null' => 0,
            			'multiple' => 0,
            			'allow_archives' => 0,
            		),
            		array(
            			'key' => 'field_5be21f0b19e1d',
            			'label' => 'Background Color',
            			'name' => 'background_color',
            			'type' => 'radio',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array(
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'choices' => array(
            				'green' => 'Green',
            				'orange' => 'Orange',
            				'blue' => 'Blue',
            				'red' => 'Red',
            			),
            			'allow_null' => 0,
            			'other_choice' => 0,
            			'default_value' => 'green',
            			'layout' => 'vertical',
            			'return_format' => 'label',
            			'save_other_choice' => 0,
            		),
    						array(
    							'key' => 'field_5b353b9d33efc',
    							'label' => 'Full Width Color Content',
    							'name' => 'post_full_width_color_content',
    							'type' => 'textarea',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array(
    								'width' => '',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => '',
    							'placeholder' => '',
    							'maxlength' => '',
    							'rows' => '',
    							'new_lines' => '',
    						),
            		array(
            			'key' => 'field_5be220e69467b',
            			'label' => 'Button Label',
            			'name' => 'button_label',
            			'type' => 'text',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array(
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            			'placeholder' => '',
            			'prepend' => '',
            			'append' => '',
            			'maxlength' => '',
            		),
            		array(
            			'key' => 'field_5be220ec9467c',
            			'label' => 'Button Link',
            			'name' => 'button_link',
            			'type' => 'page_link',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array(
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'post_type' => '',
            			'taxonomy' => '',
            			'allow_null' => 0,
            			'allow_archives' => 1,
            			'multiple' => 0,
            		),
    					),
    					'min' => '',
    					'max' => '',
    				),
    				'5b353cc6a25c6' => array(
    					'key' => '5b353cc6a25c6',
    					'name' => 'post-block_quote',
    					'label' => 'Block Quote',
    					'display' => 'block',
    					'sub_fields' => array(
    						array(
    							'key' => 'field_5b353c00127d7',
    							'label' => 'Block Quote',
    							'name' => 'post_block_quote',
    							'type' => 'textarea',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array(
    								'width' => '50',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => '',
    							'placeholder' => '',
    							'maxlength' => '',
    							'rows' => '',
    							'new_lines' => '',
    						),
    						array(
    							'key' => 'field_5b353c3f127d8',
    							'label' => 'Block Quote Citation',
    							'name' => 'post_block_quote_citation',
    							'type' => 'text',
    							'instructions' => 'Optional citation for Block Quote.',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array(
    								'width' => '50',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => '',
    							'placeholder' => '',
    							'prepend' => '',
    							'append' => '',
    							'maxlength' => '',
    						),
    					),
    					'min' => '',
    					'max' => '',
    				),
    			),
    			'button_label' => 'Add Row',
    			'min' => '',
    			'max' => '',
    		),
    	),
    	'location' => array(
    		array(
    			array(
    				'param' => 'post_type',
    				'operator' => '==',
    				'value' => 'post',
    			),
    		),
    	),
    	'menu_order' => 2,
    	'position' => 'acf_after_title',
    	'style' => 'default',
    	'label_placement' => 'top',
    	'instruction_placement' => 'label',
    	'hide_on_screen' => array(
    		0 => 'the_content',
    	),
    	'active' => 1,
    	'description' => '',
    ));

    endif;
  }
}
