<?php
namespace AmericasFarmers;

class ACFTemplateFields
{
	public static function setupTemplateFields()
	{
		self::setupFlexContentFields();
	}

	private static function setupFlexContentFields()
	{
		if( function_exists('acf_add_local_field_group') ):

			acf_add_local_field_group(array(
					'key' => 'group_5b0d7b2c7296b',
					'title' => 'Flexible Content',
					'fields' => array(
						array(
							'key' => 'field_5b0d7b6380629',
							'label' => 'Flexible Content',
							'name' => 'flexible_content',
							'type' => 'flexible_content',
							'instructions' => 'Add as many flexible content blocks as you\'d like.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(

							'5b3a7411b23e726' => array(
								'key' => '5b3a7411b23e726',
								'name' => 'rural_enrollment',
								'label' => 'Program Enrollment',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5eab180234jlsd',
										'label' => 'Grow Program Enrollment',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'This field will add the Phase based fields to the page in the place we would like them to be.',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
									array(
										'key' => 'field_5ea218cd76543',
										'label' => 'Enroll Program',
										'name' => 'enroll_program',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'program',
										),
										'taxonomy' => '',
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'object',
										'ui' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b292c3a1e156' => array(
								'key' => '5b292c3a1e156',
								'name' => 'get_nominations',
								'label' => 'Get Nominations',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b292c481e157',
										'label' => 'nominations_message',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'This will render out the module for checking for nominations',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b3a74112983hj4ls' => array(
								'key' => '5b3a7411b2384ir',
								'name' => 'story_phase',
								'label' => 'Program Story',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5eab18012lk3j',
										'label' => 'Grow Program Story',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'This field will add the Phase based fields to the page in the place we would like them to be.',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
									array(
										'key' => 'field_5ea218cd213487',
										'label' => 'Active Program',
										'name' => 'active_program',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'program',
										),
										'taxonomy' => '',
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'object',
										'ui' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),
							'announce_finalists_key' => array(
								'key' => 'announce_finalists_key',
								'name' => 'announce_finalists',
								'label' => 'Announce Finalists',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_finalist_year_header',
										'label' => 'Year Display Header',
										'name' => 'year_display_header',
										'type' => 'text',
										'instructions' => 'Type the year that these finalists were selected.',
									),
									array(
										'key' => 'field_finalist_content',
										'label' => 'Content Blurb',
										'name' => 'content_blurb',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_finalist_program',
										'label' => 'Program',
										'name' => 'program',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'program',
										),
										'taxonomy' => array(
										),
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'id',
										'ui' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b228b5c2e6d5' => array(
								'key' => '5b228b5c2e6d5',
								'name' => 'announce_winners',
								'label' => 'Announce Winners',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5eab1a901a7d7',
										'label' => 'Grow Program Enrollment',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'This field will add the Phase based fields to the page in the place we would like them to be.',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
									array(
										'key' => 'field_5ea218cd3ff9d',
										'label' => 'Winners Program',
										'name' => 'program',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'program',
										),
										'taxonomy' => '',
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'object',
										'ui' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b228b5c28723h' => array(
								'key' => '5b228b5c2e2782k',
								'name' => 'GRE_winners',
								'label' => 'Grow Rural Education Winners',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5eab1a902762872',
										'label' => 'Winners',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'This will allow for the winners to be displayed on a page without using the phase based logic.',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
									array(
										'key' => 'field_5ea218c27836',
										'label' => 'Winners Program',
										'name' => 'program',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'program',
										),
										'taxonomy' => '',
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'object',
										'ui' => 1,
									),
								),
								'min' => '',
								'max' => '',
							),

							'5b0d7b6b7ad3413' => array(
								'key' => '5b0d7b6b7ad3414',
								'label' => 'Submit A Nomination',
								'name' => 'nomination_callout',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b3a2342323423447432be727',
										'label' => 'Current Program',
										'name' => 'current_program',
										'type' => 'post_object',
										'instructions' => 'Select the program that this is calling out. This will automatically toggle the colors on the button and such.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'program',
										),
										'taxonomy' => array(
										),
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'object',
										'ui' => 1,
									),
									array(
										'key' => '5b0d7b6b7ad3414',
										'label' => 'Program Logo',
										'name' => 'small_logo',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array(
										'key' => '5b0d7b6b7ad3415',
										'label' => 'Headline',
										'name' => 'nomination_callout_headline',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
									),
									array(
										'key' => '5b0d7b6b7ad3416',
										'label' => 'Content',
										'name' => 'nomination_callout_content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
									),
									array(
										'key' => '5b0d7b6b7ad3417',
										'label' => 'Button Text',
										'name' => 'nomination_button_text',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
									),
									array(
										'key' => '5b0d7b6b7ad3418',
										'label' => 'Button URL',
										'name' => 'nomination_button_url',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b0d7b6b7ad15' => array(
							'key' => '5b0d7b6b7ad15',
							'name' => 'wysiwyg_content',
							'label' => 'Basic WYSIWYG Content',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5b0d7c488062a',
									'label' => 'Content',
									'name' => 'content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
							'5b0324d7b6b7ad16' => array(
								'key' => '5b0d7b6b71234ad16',
								'name' => 'image_callout',
								'label' => 'Image Callout',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b0d7c488062c',
										'label' => 'Content',
										'name' => 'image_callout_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '75',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5b156870968d4',
										'label' => 'Background Image',
										'name' => 'image_callout_background_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
												'width' => '25',
												'class' => '',
												'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b0324d7b6b712984' => array(
								'key' => '5b0d7b6b712028263t',
								'name' => 'video_callout',
								'label' => 'Video Callout',
								'display' => 'block',
								'sub_fields' => array(
									//Added this just in case we need it in the future!
									// array(
									// 	'key' => 'field_5ea0a90c70f87',
									// 	'label' => 'Align Text',
									// 	'name' => 'align_text',
									// 	'type' => 'radio',
									// 	'instructions' => '',
									// 	'required' => 1,
									// 	'conditional_logic' => 0,
									// 	'wrapper' => array(
									// 		'width' => '',
									// 		'class' => '',
									// 		'id' => '',
									// 	),
									// 	'choices' => array(
									// 		'Left' => 'Left',
									// 		'Right' => 'Right',
									// 	),
									// 	'allow_null' => 0,
									// 	'other_choice' => 0,
									// 	'default_value' => '',
									// 	'layout' => 'vertical',
									// 	'return_format' => 'value',
									// 	'save_other_choice' => 0,
									// ),
									array(
										'key' => 'field_5ea0a98170f88',
										'label' => 'Video Section',
										'name' => 'video_section',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array(
										'key' => 'field_5ea0aa5670f89',
										'label' => 'Video IFrame',
										'name' => 'video_iframe',
										'type' => 'text',
										'instructions' => 'Add IFrame for youtube',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5ea0aab070f8a',
										'label' => 'Video Content',
										'name' => 'video_content',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array(
										'key' => 'field_5ea0aacc70f8b',
										'label' => 'Video Title',
										'name' => 'video_title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ea0aaeasdf370f8c',
										'label' => 'Content',
										'name' => 'video_content_wysiwyg',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
								),
							),
							'5b0324d7b6b7ad21' => array(
								'key' => '5b0d7b6b71234ad21',
								'name' => 'announcement_callout',
								'label' => 'Announcement Callout',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b0d7c488063',
										'label' => 'Announcement Headline',
										'name' => 'announcement_headline',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'rows' => '2',
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b0324d7b6b7ad15' => array(
								'key' => '5b0d7b6b71234ad15',
								'name' => 'program_announcements',
								'label' => 'Program Cards',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5eab1a901a7d7asdf',
										'label' => '',
										'name' => '',
										'type' => 'message',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => 'This field will add the content for this section that is set under "Theme Config".',
										'new_lines' => 'wpautop',
										'esc_html' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
							'5b0324d7b6b7ad232' => array(
								'key' => '5b0d7b6b71234ad23',
								'name' => 'related_links',
								'label' => 'Related Links',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b241f238158a',
										'label' => 'Related Links',
										'name' => 'related_links_selection',
										'type' => 'relationship',
										'instructions' => 'Select posts or pages to be featured as related posts.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'page',
											1 => 'post',
										),
										'taxonomy' => array(
										),
										'filters' => array(
											0 => 'search',
											1 => 'post_type',
										),
										'elements' => '',
										'min' => '',
										'max' => '3',
										'return_format' => 'id',
									),
								),
								'location' => array(
									array(
										array(
											'param' => 'post_type',
											'operator' => '==',
											'value' => 'post',
										),
									),
								),
								'menu_order' => 0,
								'position' => 'normal',
								'style' => 'default',
								'label_placement' => 'top',
								'instruction_placement' => 'label',
								'hide_on_screen' => '',
								'active' => 1,
								'description' => '',
							),
							'5b16a08d777d6' => array(
								'key' => '5b16a08d777d6',
								'name' => 'document_download_section',
								'label' => 'Document Download Section',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b16a09b2cd63',
										'label' => 'Header',
										'name' => 'download_section_header',
										'type' => 'text',
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
									),
									array(
										'key' => 'field_5b16a0b32cd64',
										'label' => 'Content',
										'name' => 'download_section_content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'new_lines' => '',
									),
									array(
										'key' => 'field_5b16a0e12cd65',
										'label' => 'Document Download',
										'name' => 'document_download',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Document',
										'sub_fields' => array(
											array(
												'key' => 'field_5b16a1c52cd66',
												'label' => 'Title',
												'name' => 'title',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5b16a1ce2cd67',
												'label' => 'Sub Title',
												'name' => 'sub_title',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5b16a2042cd68',
												'label' => 'File',
												'name' => 'file',
												'type' => 'file',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'url',
												'library' => 'all',
												'min_size' => '',
												'max_size' => '',
												'mime_types' => '',
											),
											array(
												'key' => 'field_5b16a2372cd69',
												'label' => 'Background Image',
												'name' => 'background_image',
												'type' => 'image',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'url',
												'preview_size' => 'thumbnail',
												'library' => 'all',
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => 1,
												'mime_types' => '',
											),
										),
									),
								),
							),
							'5b0d7b6b71234ad29' => array(
								'key' => '5b0d7b6b71234ad29',
								'name' => 'step_by_step',
								'label' => 'Step By Step',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5eb1895331e9f',
										'label' => 'Step Header',
										'name' => 'step_header',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5eb1897431ea0',
										'label' => 'Step Content',
										'name' => 'step_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5eb185a3b1f99',
										'label' => 'Steps',
										'name' => 'steps',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'table',
										'button_label' => '',
										'sub_fields' => array(
											array(
												'key' => 'field_5eb185b7b1f9a',
												'label' => 'Step Number',
												'name' => 'step_number',
												'type' => 'number',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => '',
												'max' => '',
												'step' => '',
											),
											array(
												'key' => 'field_5eb185ddb1f9b',
												'label' => 'Step Content',
												'name' => 'step_content',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'full',
												'media_upload' => 1,
												'delay' => 0,
											),
										),
									),
								 ),
								'min' => '',
								'max' => '',
							),
							'5b0324d7b6b7ad2424' => array(
								'key' => '5b0324d7b6b7ad2424',
								'name' => 'faqs',
								'label' => 'Frequently Asked Questions',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b16a1c52cd66_faq_title',
										'label' => 'FAQ Section Title',
										'name' => 'faq_section_title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5b16a1c52cd66_faq_subtitle',
										'label' => 'FAQ Section Subtitle',
										'name' => 'faq_section_subtitle',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
	
									array(
										'key' => '5b0324d7b6b7ad2425',
										'label' => 'FAQ',
										'name' => 'faq',
										'type' => 'repeater',
										'layout' => 'block',
										'button_label' => 'Add New FAQ',
										'sub_fields' => array(
											array(
												'key' => 'field_5b0324d7b6b7ad2426',
												'label' => 'Question',
												'name' => 'faq_question',
												'type' => 'textarea',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 1,
												'delay' => 0,
											),
											array(
												'key' => 'field_5b0324d7b6b7ad2427',
												'label' => 'Answer',
												'name' => 'faq_answer',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 1,
												'delay' => 0,
											),
										),
									),
								),
								'min' => '',
								'max' => '',
							),
							//New Layouts would go here
							'5b3a634434224' => array(
								'key' => '5b3a634434224',
								'name' => 'recent_stories_component',
								'label' => 'Recent Stories',
								'sub_fields' => array(
									array(
										'key' => 'field_show_recent_stories',
										'label' => 'Show Recent Stories',
										'name' => 'show_recent_stories',
										'type' => 'true_false',
										'message' => 'Check here if you would like to pull in recent Stories.',
										'required' => 0,
									),
									array(
										'key' => 'field_select_recent_stories',
										'label' => 'Select Stories Category',
										'name' => 'select_stories_category',
										'type' => 'taxonomy',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'taxonomy' => 'category',
										'field_type' => 'checkbox',
										'add_term' => 1,
										'save_terms' => 0,
										'load_terms' => 0,
										'return_format' => 'id',
										'multiple' => 0,
										'allow_null' => 0,
									),
								),
							),
							'5b15943443984j' => array(
								'key' => '5b15943432093s',
								'name' => 'fifty_fifty_repeaters',
								'label' => 'Fifty Fifty Media Text',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_fifty_fifty_section_headline',
										'label' => 'Section Headline',
										'name' => 'section_headline',
										'type' => 'text',
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
									),
									array(
										'key' => 'field_fifty_fifty_section_content',
										'label' => 'Intro Content',
										'name' => 'intro_content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'rows' => 3,
									),
									array(
										'key' => 'field_5eac74da63d1c',
										'label' => 'Media Section',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array(
										'key' => 'field_5eac761663d1d',
										'label' => 'Media Image',
										'name' => 'media_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5eac76be63d1f',
										'label' => 'Text Section',
										'name' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
										'endpoint' => 0,
									),
									array(
										'key' => 'field_fifty_fifty_background_color',
										'label' => 'Background Color',
										'name' => 'background_color',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'none' => 'None',
											'navy' => 'Navy',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
										'save_other_choice' => 0,
									),
									array(
										'key' => 'field_5eac76cb63d20',
										'label' => 'Text Repeater',
										'name' => 'text_repeater',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'table',
										'button_label' => '',
										'sub_fields' => array(
											array(
												'key' => 'field_5eac777163d21',
												'label' => 'Repeater Content',
												'name' => 'repeater_content',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'full',
												'media_upload' => 1,
												'delay' => 0,
											),
											array(
												'key' => 'field_5eac77c163d22',
												'label' => 'Button Repeater',
												'name' => 'button_repeater',
												'type' => 'repeater',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'collapsed' => '',
												'min' => 0,
												'max' => 0,
												'layout' => 'table',
												'button_label' => '',
												'sub_fields' => array(
													array(
														'key' => 'field_5eac77cd63d23',
														'label' => 'Buttons',
														'name' => 'buttons',
														'type' => 'link',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'return_format' => 'array',
													),
												),
											),
										),
									),
								),
							),
							'5b159434328a7' => array(
								'key' => '5b159434328a7',
								'name' => 'people_component',
								'label' => 'People Component',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b1594610bef7',
										'label' => 'Person',
										'name' => 'people_item',
										'type' => 'repeater',
										'layout' => 'block',
										'button_label' => 'Add Person',
										'sub_fields' => array(
											array(
												'key' => 'field_5b1594800bef8',
												'label' => 'Image',
												'name' => 'person_image',
												'type' => 'image',
												'return_format' => 'ID',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '40',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_person_headline',
												'label' => 'Name',
												'name' => 'person_headline',
												'type' => 'text',
												'wrapper' => array(
													'width' => '60',
													'class' => '',
													'id' => '',
												),
											),
											array(
												'key' => 'field_person_subheadline',
												'label' => 'State and City',
												'name' => 'person_subheadline',
												'type' => 'text',
												'wrapper' => array(
													'width' => '60',
													'class' => '',
													'id' => '',
												),
											),
											array(
												'key' => 'field_person_content',
												'label' => 'Content',
												'name' => 'person_content',
												'type' => 'textarea',
												'new_lines' => 'br'
											)
										),
									),
								),
							),
						),
						'button_label' => 'Add Row',
						'min' => '',
						'max' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'page_template',
							'operator' => '==',
							'value' => 'page-flex-content.php',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'the_content',
					1 => 'comments',
				),
				'active' => 1,
				'description' => '',
			));

			endif;
	}
}
